"""Added face_descriptor column to user as shifting face unlock logic from backend to frontend

Revision ID: b33bc67c1c81
Revises: 
Create Date: 2025-08-30 14:05:45.422319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33bc67c1c81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_descriptor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('face_descriptor')

    # ### end Alembic commands ###
